//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class Bangluong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhanvien fNhanvienID;
        [Association(@"BangluongReferencesNhanvien")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        double fNam;
        public double Nam
        {
            get { return fNam; }
            set { SetPropertyValue<double>(nameof(Nam), ref fNam, value); }
        }
        double fThang;
        public double Thang
        {
            get { return fThang; }
            set { SetPropertyValue<double>(nameof(Thang), ref fThang, value); }
        }
        double fSogiolam;
        public double Sogiolam
        {
            get { return fSogiolam; }
            set { SetPropertyValue<double>(nameof(Sogiolam), ref fSogiolam, value); }
        }
        [PersistentAlias("ToDecimal([NhanvienID]) * [Sogiolam]")]
        public string Luong
        {
            get { return (string)(EvaluateAlias(nameof(Luong))); }
        }
    }

}
