//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class Donnhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        SanPham fSanphamID;
        [Association(@"DonnhapReferencesSanPham")]
        public SanPham SanphamID
        {
            get { return fSanphamID; }
            set { SetPropertyValue<SanPham>(nameof(SanphamID), ref fSanphamID, value); }
        }
        Phieunhap fNhapID;
        [Association(@"DonnhapReferencesPhieunhap")]
        public Phieunhap NhapID
        {
            get { return fNhapID; }
            set { SetPropertyValue<Phieunhap>(nameof(NhapID), ref fNhapID, value); }
        }
        double fSoluong;
        public double Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<double>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fDongia;
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        [PersistentAlias("ToDecimal([Soluong]) * [Dongia]")]
        public decimal Thanhtien
        {
            get { return (decimal)(EvaluateAlias(nameof(Thanhtien))); }
        }
    }

}
