//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class HoadonCT : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Hoadon fHoadonID;
        [Association(@"HoadonCTReferencesHoadon")]
        public Hoadon HoadonID
        {
            get { return fHoadonID; }
            set { SetPropertyValue<Hoadon>(nameof(HoadonID), ref fHoadonID, value); }
        }
        SanPham fSanphamID;
        [Association(@"HoadonCTReferencesSanPham")]
        public SanPham SanphamID
        {
            get { return fSanphamID; }
            set { SetPropertyValue<SanPham>(nameof(SanphamID), ref fSanphamID, value); }
        }
        double fSoluong;
        public double Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<double>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fDongia;
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        [PersistentAlias("ToDecimal([Soluong]) * [Dongia]")]
        public decimal Thanhtien
        {
            get { return (decimal)(EvaluateAlias(nameof(Thanhtien))); }
        }
        [Association(@"TieuhaoReferencesHoadonCT"), Aggregated]
        public XPCollection<Tieuhao> Tieuhaos { get { return GetCollection<Tieuhao>(nameof(Tieuhaos)); } }
    }

}
